---
- name: Install OpenShift on AWS
  ansible.builtin.shell: |
    [ -f install-config.yaml ] && cp install-config.yaml install-config.yaml.orig ||:
    ./openshift-install create cluster
  environment: '{{ aws_env|from_yaml }}'
  args:
    chdir: '{{ tmp_dir }}'
    creates: '{{ kubeconfig }}'
  register: installer_run

- name: Backup original kubeconfig
  ansible.builtin.copy:
    src: '{{ kubeconfig }}'
    dest: '{{ kubeconfig }}_ORIGINAL'
  when: installer_run.changed
