---
- name: Ensure that the cluster tmp directory exists
  ansible.builtin.file:
    path: '{{ tmp_dir }}'
    state: directory

- include_tasks: byo_cert.yml
  when:
    - byo_cert_fullchain_path is defined
    - byo_cert_fullchain_path != ""
    - byo_cert_key_path is defined
    - byo_cert_key_path != ""

- include_tasks: create_users.yml
  when: create_users

- include_tasks: autoscale.yml
  when:
  - autoscale|bool
  - cluster_name != "crc"

- include_tasks: metrics_storage.yml
  when:
  - add_metrics_storage|bool
  - cluster_name != "crc"
