---
- hosts: localhost
  pre_tasks:
    - name: Look for default defined variables
      include_vars: ../vars/cluster.yml
      when: cluster_included is not defined or not cluster_included

    - fail:
        msg: Unable to continue without cluster variables set
      when: cluster_included is not defined or not cluster_included

  tasks:
    - name: Ensure we're destroying the right cluster
      pause:
        prompt: |-

          Do you want to destroy {{ full_cluster_name }} (y/n Default: N)?
      register: destroy_cluster

    - name: Determine if we should delete the tmp directory
      pause:
        prompt: |-

          Do you want to remove {{ tmp_dir }} as well (y/n Default: N)?
      register: destroy_tmp

    - name: Destroy the cluster
      ansible.builtin.shell: |
        export KUBECONFIG='{{ tmp_dir }}/auth/kubeconfig'
        ./openshift-install destroy cluster
      environment: '{{ aws_env|from_yaml }}'
      args:
        chdir: '{{ tmp_dir }}'
        removes: '{{ tmp_dir }}/auth/kubeconfig'
      when:
        - destroy_cluster.user_input.strip()|upper == 'Y'

    - name: Delete tmp directory
      ansible.builtin.file:
        path: '{{ tmp_dir }}'
        state: absent
      when:
        - destroy_tmp.user_input.strip()|upper == "Y"
